CREATE TABLE VENUE (
    LEVEL_ID INT IDENTITY NOT NULL PRIMARY KEY AUTO_INCREMENT,
    LEVEL_NAME VARCHAR(100) NOT NULL,
    PRICE DECIMAL NOT NULL,
    NUMBER_OF_ROW INT,
    SEATS_IN_ROW INT
);

CREATE TABLE CUSTOMER (
    ID BIGINT IDENTITY NOT NULL PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(100) NOT NULL,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50)
);

ALTER TABLE CUSTOMER ADD CONSTRAINT EMAIL_UNIQUE UNIQUE(EMAIL);

CREATE TABLE SEAT_HOLD (
    ID INT IDENTITY NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID BIGINT NOT NULL,
    HOLD_TIME TIMESTAMP DEFAULT NULL,
    RESERVATION_CONFIRMATION_CODE VARCHAR(300),
    RESERVATION_TIME TIMESTAMP DEFAULT NULL,
    CONSTRAINT CUSTOMER_SEAT_HOLD_FK FOREIGN KEY (CUSTOMER_ID)
    REFERENCES CUSTOMER(ID)
);

CREATE TABLE SEAT_ORDER (
    HOLD_ID INT NOT NULL,
    VENUE_ID INT NOT NULL,
    NUMBER_OF_SEATS INT NOT NULL,
    CONSTRAINT SEAT_HOLD_ORDER_FK FOREIGN KEY (HOLD_ID)
    REFERENCES SEAT_HOLD(ID),
    CONSTRAINT VENUE_ORDER_FK FOREIGN KEY (VENUE_ID)
    REFERENCES VENUE(LEVEL_ID)
);

CREATE SEQUENCE CUSTOMER_SEQ;
CREATE SEQUENCE SEAT_HOLD_SEQ;
CREATE SEQUENCE SEAT_ORDER_SEQ;